---
- hosts: winhost
  gather_facts: true

  tasks:
  - name: check that folder exists
    win_stat:
      path: C:\ACLtest
    register: folderPresent

  - name: cut ACL inheritance and copy existing ones
    win_acl_inheritance:
      path: C:\ACLtest
      state: absent
      reorganize: yes
    when: folderPresent.stat.exists

  - name: Add write right for authenticated users
    win_acl:
      path: C:\ACLtest
      user: toweradmin
      rights: Write
      type: allow
      state: present
      inherit: ContainerInherit, ObjectInherit
      propagation: 'InheritOnly'
    when: folderPresent.stat.exists

#  - name: Non-Win :: Obtain the ACL for a specific file
#    acl:
#      path: C:\ACLtest
#    register: acl_info
