---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

#  vars_prompt:
#  - name: source
#    prompt: Source
#    private: no
#
#  - name: destination
#    prompt: destination
#    private: no
#
#  - name: merge_filename_regex
#    prompt: merge_filename_regex
#    private: no
#
#  - name: merged_file_separator_text
#    prompt: merged_file_separator_text
#    private: no

  vars:
    source: /root/auto/
    destination: /root/auto/
    merge_filename_regex: "\\.csv"
#    merge_filename_regex: "\\.(txt|csv)"
    merged_file_separator_text: ","

  tasks:
  - name: Merge raw contents from all data filesystem
    assemble:
      src: "{{ source }}"
      dest: "{{ destination }}"
      regexp: "{{ merge_filename_regex }}"
      validate: /root/auto/ -t -f %s
      delimiter: "{{ merged_file_separator_text }}"
    register: merge_results

  - debug:
      msg: "Files merge and placed in {{ merge_results }}"
