---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

  vars:
    source: /home/ansible/automation
    destination: /home/ansible/merged_data/merged_installed.csv

  tasks:
  - name: Create /home/ansible/merged_data if it does not exist
    ansible.builtin.file:
      path: /home/ansible/merged_data
      state: directory
      mode: '0755'

  - name: Create /home/ansible/automation if it does not exist
    ansible.builtin.file:
      path: /home/ansible/automation
      state: directory
      mode: '0755'

  - name: Remove merged file
    ansible.builtin.file:
      path: /home/ansible/merged_data/merged_installed.csv
      state: absent

  - name: Merge raw contents from all data filesystem
    assemble:
      src: "{{ source }}"
      dest: "{{ destination }}"

  - name: datestamp for archive file
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp

  - name: Set var for datestamp
    set_fact:
     cur_date: "{{ tstamp.stdout[0:10]}}"
     cur_time: "{{ tstamp.stdout[10:]}}"

  - name: Archive to gz file type
    archive:
      path: /home/ansible/merged_data
      dest: "/home/ansible/merged_data/PatchingReport-{{ cur_date }}:{{ cur_time }}.gz"
      format: gz

    - name: Housekeeping - find all files that are older than 10 days
      find:
        paths: /home/ansible/merged_data
        age: 10d
        recurse: yes
      register: filesOlderThan10

    - name: Housekeeping - remove older than 10
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ filesOlderThan10.files }}"
