---
- hosts: winhost, localhost
  gather_facts: true

# can be amended via 'prompt on launch'
  vars:
  - source_path: C:\ALM\copy.txt
  - dest_path: /home/

  tasks:
  - name: Copy files from Win to AT
    fetch:
      src: "{{ source_path }}"
      dest: "{{ dest_path }}"
      flat: yes
      validate_checksum: no
    register: file_copy
