---
- hosts: all
  gather_facts: false

# can be amended via 'prompt on launch'
  vars:
  - source_path:
  - at_path:
  - dest_path:

  tasks:
# Copying ALM log files from all 11 windows boxes to a group share
  - name: Copy files from Windows to AT
    fetch:
      src: "{{ source_path }}"
      dest: "{{ at_path }}"
#      dest: "{{ dest_path }}"
      flat: yes
      ignore_errors: yes
#      validate_checksum: no
    register: file_copy

#  - name: Copy files from AT to share
#    fetch:
#      src: "{{ at_path }}"
#      dest: "{{ dest_path }}"
#      flat: yes
#      validate_checksum: no
#    register: file_copy

#  - name:
#    fail:
#      msg: " Files copied to {{ dest_path }} "
#    when: file_copy.failed == true

# Housekeeping - If files have copied delete old files
# if file_copy.failed == true then rm etc
