---
- hosts: winhost, localhost
  gather_facts: true

# can be amended via 'prompt on launch'
#  vars:
#  - source_path:
#  - at_path:
#  - dest_path:

  tasks:
  - name: Copy files from Win to AT
    fetch:
#      src: "{{ at_path }}"
      src: \\192.168.56.210\ALM\Copy.txt
#      dest: "{{ dest_path }}"
      dest: /localhost/home/
      remote_src: yes
