---
- hosts: localhost
  gather_facts: true

  tasks:
  - name: Recursively find ALM files
    find:
      paths: /var/lib/docker/
      patterns: '*.txt,*.alm.*'
      age: 1000000m
      recurse: yes
      file_type: file
      excludes: 'nginx,mysql'
    register: files_matched

  - debug:
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

#  - name: Jump2 - Copy files from AT to Win
#    fetch:
#      src: /home/ALM
#      remote_src: yes
#      dest: "{{ jump2_dest }}"
#      flat: yes
#      validate_checksum: no
#    register: file_copy
