---
- hosts: winhost
  gather_facts: true

- name: Enable and remove dedicated ACE's
  win_acl_inheritance:
    path: C:\ACLtest
    state: present
    reorganize: True

  - name: Obtain the ACL for a specific file
    acl:
      path: C:\ACLtest
    register: acl_info
