---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root

  tasks:
#  - name: Recursively find ALM files
#    find:
#      paths: /var/lib/docker/overlay2/
#      patterns: "ALM*.txt"
#      age: 1000000m
#      recurse: yes
#      file_type: file
#      excludes: 'nginx,mysql'
#    register: files_matched

#  - name: Print files
#    debug:
#      msg: "{{ item.path }}"
#    with_items: "{{ files_matched.files }}"

  - name: recurse path
    find:
      path: /var/lib/docker/overlay2
      recurse: yes
#      patterns: "wrapper.txt,SaServerLog_*.html,QcLog_*.html"
      patterns: "wrapper.txt"
#      file_type: file
#      age: 10m
    register: files

  - name: Print files
    debug:
      msg: "{{ item.path }}"

  - name: copy files
    copy:
      src: "{{item.path}}"
      dest: /home/ALM
    with_items: "{{files.files}}"
