---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

  vars:
    source: /root/auto/
    destination: /root/merge.csv
    merge_filename_regex: "\\.csv"
#    merge_filename_regex: "\\.(txt|csv)"
    merged_file_separator_text: ","

  tasks:
  - name: Merge raw contents from all data filesystem
    assemble:
      src: "{{ source }}"
      dest: "{{ destination }}"
#      regexp: "{{ merge_filename_regex }}"
#      validate: /root/auto/ -t -f %s
#      delimiter: "{{ merged_file_separator_text }}"
    register: merge_results

  - name: displaying merge_result var to screen
    debug:
      msg: "csv files merged & saved to /root/merge.csv \n\n {{ merge_results }}"
