---
- hosts: winhost
  gather_facts: true
# New creds created for windows and linux

# can be amended via 'prompt on launch'
  vars:
  - source_path: C:\ALM\Source\ALMCopy.txt
  - dest_path: /home/toweradmin/

  tasks:
  - name: Copy files from Win to AT
    fetch:
      src: "{{ source_path }}"
      remote_src: yes
      dest: "{{ dest_path }}"
      flat: yes
      validate_checksum: no
    register: file_copy

# find / -name Copy.txt
# /var/lib/docker/overlay2/1b836df67ce867bee8d656c3cb71d21f48874c92f92c0be694f25bcea5cada23/merged/localhost/home/winhost/C:/ALM/Copy.txt
