---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

  vars:
    source: /root/auto/
    destination: /root/merge/merged_installed.csv
#    merge_filename_regex: "\\.csv"
#    merge_filename_regex: "\\.(txt|csv)"
#    merged_file_separator_text: ","

  tasks:
  - name: Create /root/merged_data/ if it does not exist
    ansible.builtin.file:
      path: /root/merged_data
      state: directory
      mode: '0755'

  - name: Create /root/automation/ if it does not exist
    ansible.builtin.file:
      path: /root/automation
      state: directory
      mode: '0755'

  - name: Merge raw contents from all data filesystem
    assemble:
      src: "{{ source }}"
      dest: "{{ destination }}"
#      regexp: "{{ merge_filename_regex }}"
#      validate: /root/auto/ -t -f %s
#      delimiter: "{{ merged_file_separator_text }}"
#    register: merge_results

#  - name: displaying merge_result var to screen
#    debug:
#      msg: "{{ merge_results }}"

  - name: datestamp for archive file
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp

  - name: Set var for datestamp
    set_fact:
     cur_date: "{{ tstamp.stdout[0:10]}}"
     cur_time: "{{ tstamp.stdout[10:]}}"

  - name: Archive to gz file type
    archive:
      path: /root/merged_data
      dest: "/root/merged_data/PatchingReport-{{ cur_date }}:{{ cur_time }}.gz"
      format: gz
