---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root

  tasks:
  - name: Recursively find ALM files
    find:
      paths: /var/lib/docker/overlay2/
      patterns: "ALM*.txt"
#      age: 1000000m
      recurse: yes
#      file_type: file
#      excludes: 'nginx,mysql'
    register: files_matched

  - debug: Print matched files to screen
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

#  - name: Jump2 - Copy files from AT to Win
#    fetch:
#      src: /home/ALM
#      remote_src: yes
#      dest: "{{ jump2_dest }}"
#      flat: yes
#      validate_checksum: no
#    register: file_copy
