---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

  tasks:
  - name: Pre change disk check
    command: df -hT /home/toweradmin/logs
    register: space

  - name: Print the filesystem usage before any activity has been taken
    debug:
      var: space.stdout_lines

  - name: Execute the Uptime command over Command module
    command: "uptime"
    register: uptimeoutput

  - name: Print server uptime
    debug:
      var: uptimeoutput.stdout_lines

  - name: Store the filesystem usage output in /home/toweradmin/logs/DiskSpacePreArchive.log
    copy:
      content: "{{ space.stdout_lines }} {{ uptimeoutput.stdout_lines }}"
#      dest: "/home/toweradmin/logs/DiskSpace-{{ansible_date_time.iso8601}}.log"
      dest: "/home/toweradmin/logs/DiskSpace{{date}}.txt"
