#---
#- hosts: winhost
#
#  tasks:
#  - name:
#    fetch:
#      src: \\192.168.56.210\\c$\temp#
#      dest: \\192.168.56.210\\c$

---
- name: Sync Files
  hosts: winhost

  tasks:
  - name: Sync
    win_robocopy:
      src: c:\temp\Test_Host.txt
      dest: \\win-host\c$
      flags: Test_Host.txt /E /PURGE /XD SOME_DIR /XF SOME_FILE /MT:32
