---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root


  tasks:
  - name: Ansible fact - ansible_date_time
    debug:
     var: ansible_date_time

  - name: Ansible fact - ansible_date_time.iso8601
    debug:
     msg: "Timestamp in the ISO8601 format: {{ ansible_date_time.iso8601 }}"
