#---
#- hosts: winhost
#
#  tasks:
#  - name:
#    fetch:
#      src: \\192.168.56.210\\c$\temp#
#      dest: \\192.168.56.210\\c$

---
- name: Sync Files
  hosts: winhost

  tasks:
  - name: Sync ServerA to ServerB
    win_robocopy:
      src: "C:\\Temp\\Test_Host.txt"
      dest: "\\192.168.56.210\\c$"
      recurse: true
      purge: true
