---
- hosts: node1

  tasks:
  - name: Get timestamp from the system
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp

  - name: Set variables
    set_fact:
     cur_date: "{{ tstamp.stdout[0:10]}}"
     cur_time: "{{ tstamp.stdout[10:]}}"

  - name: System timestamp - date
    debug:
     msg:  "Current date: {{ cur_date }}"

  - name: System timestamp - time
    debug:
     msg:  "Current date: {{ cur_time }}"

  - name: copy info into txt - cur_time_ns
    copy:
      content:
        "{{ cur_time }}  \n\n  {{ cur_date }}"
      dest: "/home/toweradmin/logs/Datestamp:{{ cur_date }}:{{ cur_time }}.txt"
