---
- hosts: windows
  gather_facts: false
  vars:
     DiskThreshold: 5

  tasks:
  - name: running diskspace.ps1 on remote windows server
    win_shell: C:\working\DiskSpace.ps1

  - name: copy disk space information from file
    win_shell:
      Select-String -Path C:\working\DiskSpace.txt -pattern "@{FreeSpace="
    register: freespace

  - name: read file to get free disk space
    set_fact: freediskspace={{ freespace.stdout_lines }}

  - name: trim file to get free disk space value
    set_fact: data1={{ freediskspace | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: check if disk space above threshold
    set_fact:
     DiskSpace:
       "{{ (DiskThreshold | int) >= (data1 | int) }}"

  - name: Get server name
    win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: Disk Space below threshold server Information
    debug:
      msg:
        - "{{ server_name.stdout_lines[0] }} has only {{ data1 }}GB free on the C Drive"
        - "Free up some Space on the C Drive before patching commences"
    when: DiskSpace == true

  - name: Disk Space below threshold server Information
    debug:
      msg:
        - "{{ server_name.stdout_lines[0] }} has {{ data1 }}GB free on the C Drive"
    when: DiskSpace == false

  - name: running CreateCopy.ps1
    debug:
      msg:
        - "running createcopy.ps1 on {{ server_name.stdout_lines[0] }}"
    win_shell: C:\working\CreateCopy.ps1

  - name: runnning Archive.ps1
    win_shell: C:\working\Archive.ps1

  - name: running delete.ps1
    win_shell: C:\working\delete.ps1

  - name: running acl.ps1
    debug:
      msg:
        - "Finally running acl.ps1 on {{ server_name.stdout_lines[0] }}"
    win_shell: C:\working\ACL.ps1
