---
- name: Check Disk Space Usage
  hosts: windows

  vars:
   mount_all: []

  tasks:
    - name: Check /tmp freespace
      shell: df /tmp --output\=avail | tail -1
      register: tmp_freespace

    - fail:
        msg: /tmp does not have the minimum space required to continue (3Gb requested).
      when: tmp_freespace.stdout|float is lt 3000000
