---
- hosts: node1
#  gather_facts: false
  become: yes
#  remote_user: root
#  become_user: toweradmin
#  vars:
#    ansible_become_pass: P@ssw0rdAdmin

# ask for path or file, file name, inc ref and how many days old the file needs to be before deleting/archiving
# [ansible@control ~]$ ansible-playbook -i inventory zip02.yml -e "in_path=/home/toweradmin/logs in_pattern=m*.log"

  tasks:
  - name: Pre change disk check
    command: df -h
    register: space
  - debug:
      var: space.stdout_lines
  - copy:
      content: "{{ space.stdout_lines }}"
      dest: "/home/toweradmin/logs/DiskSpacePreArchive-{{ansible_date_time.iso8601}}.txt"

  - name: Ansible find file examples from {{in_path}}
    find:
      paths: "{{in_path}}"
      patterns: "{{in_pattern}}"
#      age: 24h
#      age_stamp: atime
#      recurse: yes
    register: files_matched

  - debug:
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

  - archive:
      path: "{{ item.path }}"
#      remove: True
#      dest: /var/test1gz
      format: gz
    with_items: '{{ files_matched.files }}'

  - name: delete files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: '{{ files_matched.files }}'

  - name: Post change disk check
    command: df -h
    register: space
  - debug:
      var: space.stdout_lines
  - copy:
      content: "{{ space.stdout_lines }}"
      dest: "/home/toweradmin/logs/DiskSpacePostArchive-{{ansible_date_time.iso8601}}.txt"
