---
- hosts: node1
  gather_facts: no
  tasks:

    - name: Check /tmp freespace
      shell: df /tmp --output\=avail | tail -1
      register: tmp_freespace

    - fail:
        msg: /tmp does not have the minimum space required to continue
      when: tmp_freespace.stdout|float is lt 1000
