---
- hosts: "control"
  gather_facts: no
  tasks:
    - name: add cache directory
      file:
        path: /opt/cache
        state: directory

    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: restart nginx
      service:
        name: nginx
        state: restarted
