---
- name: capacity
  hosts: node2
  become: yes
  become_user: root
  tasks:

    - name: Pre change disk check
      command: df -h
      register: space
    - debug:
        var: space.stdout_lines

    - copy:
        content: "{{ space.stdout_lines }}"
        dest: "/var/diskcap.txt"
