---
- hosts: node2
  gather_facts: false
  become: yes
#  remote_user: root
  become_user: toweradmin
  vars:
    ansible_become_pass: P@ssw0rdAdmin

# ask for path or file, file name, inc ref and how many days old the file needs to be before deleting/archiving
# Non-tower usage - [ansible@control ~]$ ansible-playbook -i inventory zip02.yml -e "in_path=/home in_pattern=m*.log"

  vars_prompt:

  - name: in_path
    prompt: Where are the files?  i.e. /home/toweradmin/logs
    private: no

  - name: in_pattern
    prompt: Whats their pattern?  i.e. message*.log
    private: no

  tasks:

  - name: Pre change disk check
    command: df -h
    register: space
  - debug:
      var: space.stdout_lines
  - copy:
      content: "{{ space.stdout_lines }}"
#      dest: "/home/toweradmin/logs/Drive-Cap-PrePB-{{ansible_date_time.iso8601}}.log"
      dest: "/home/toweradmin/logs/Drive-Cap-PrePB.log"

  - name: Ansible find file examples
    find:
      paths: "{{in_path}}"
      patterns: "{{in_pattern}}"
#      age: 24h
#      age_stamp: atime
#      recurse: yes
    register: files_matched

  - debug:
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

  - archive:
      path: "{{ item.path }}"
#      remove: True
#      dest: /var/test1gz
      format: gz
    with_items: '{{ files_matched.files }}'

  - name: delete files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: '{{ files_matched.files }}'

  - name: Post change disk check
    command: df -h
    register: space
  - debug:
      var: space.stdout_lines
  - copy:
      content: "{{ space.stdout_lines }}"
      dest: "/home/toweradmin/logs/Drive-Cap-PostPB.log"
