---
- hosts: node2
  become: True
  tasks:
    - name: find all files older than 10 days
      find:
        path: /var/*/
        age: 10d
        recursive: yes
      register: fileolderthan10

    - name: whats in fileolderthan10
      debug:
        msg: "fileolderthan10={{ fileolderthan10 }}"

#  - archive:
#      path: /var/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
