---
- hosts: node2
  become: yes
  become_user: root
  tasks:

  - name: Ansible find file examples
    find:
      paths: /home
      patterns: "message*.log"
#      age: 24h
#      age_stamp: atime
#      recurse: yes
    register: files_matched



  - debug:
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

  - archive:
      path: "{{ item.path }}"
#      remove: True
#      dest: /var/test1gz
      format: gz
    with_items: '{{ files_matched.files }}'

  - name: delete files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: '{{ files_matched.files }}'
