---
- hosts: node2
#  become: True
  tasks:
  - name: finds files
    find:
      paths: /home
#        age: 2d
#        size: 1m
#        age_stamp: 86400
      patterns: message*.log, *.tmp
#        recursive: yes
      register: messagelog1day

      debug:
        msg: "{{ messagelog1day.files }}"

#  - archive:
#      path: /var/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
