#---
#- hosts: node2
#  become: True
#  tasks:
#  - name: finds files
#    find:
#      paths: /home
#        age: 1d
#        size: 10m
#        age_stamp: 86400
#      patterns: "message*.log, *.tmp"
##        recursive: yes
#    register: messagelog

---
- hosts: node2
  tasks:
  - name: Ansible find file examples
    find:
      paths: /home
      patterns: "message*.log, *.tmp"
#      age_stamp: 86400
      age_stamp: 10
      recursive: yes
    register: files_matched

  - debug:
      msg: "{{ files_matched.files }}"

#  - archive:
#      path: /var/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
