---
- hosts: node2
  tasks:
  - name: Ansible find file examples
    find:
      paths: /home
      patterns: "*.log"
      age: 24h
      age_stamp: atime
#      recurse: yes
    register: files_matched

  - debug:
      msg: "{{ files_matched.files }}"

#  - archive:
#      path: /var/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
