---
- hosts: node2
  tasks:
  - name: Ansible find file examples
    find:
      paths: /home
      patterns: "message*.log"
#      age: 24h
#      age_stamp: atime
#      recurse: yes
    register: files_matched

  - name: create file
      file:
        path: /home/ {{ item.path }}
        state: touch
      with_items: '{{ files_matched.files }}'

  - debug:
      msg: "{{ files_matched.files }}"
      
#  - archive:
#      path: /home/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
