---
- hosts: node2
#  become: True
  tasks:
  - name: finds files
    find:
      paths: /home
#        age: 1d
#        size: 10m
#        age_stamp: 86400
      patterns: "message*.log, *.tmp"
#        recursive: yes
    register: messagelog

    - debug:
        msg: "{{ messagelog.files }}"

#  - archive:
#      path: /var/test1/
#      remove: True
#      dest: /var/test1.zip
#      format: zip
